apiVersion: v1
kind: Service
metadata:
  name: np-service
  labels: 
    app: np-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend